disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Resiliz"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "23 March 2025"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Viraj's Official website"
  copyright = "© 2024 Resiliz. All rights reserved."

 [params.author]
   name = "Resiliz"
   email = "virajamara@gmail.com"
   image = "img/logo.jpg"
   imageQuality = 96
   headline = "Powered by Resilience, Proven by Results"
   bio = "Results-driven Full Stack Developer with 8+ years of experience in startups and large-scale companies. Strong problem-solver, agile team player, and proactive communicator. Passionate about lifelong learning, innovation, and building scalable software solutions."
   links = [
     { email = "mailto:virajamara@gmail.com" },
     { link = "profile" },
     { github = "https://github.com/sameerabit" },
     { gitlab = "https://gitlab.com/virajamara" },
     { linkedin = "https://www.linkedin.com/in/viraj-amarasinghe" },
     { medium = "https://medium.com/@sameeraviraj" },
     { stack-overflow = "https://stackoverflow.com/users/3755369/viraj-amarasinghe" },
   ]
